### ISSUE TITLE
help with some queries

### ISSUE THREAD

**Issue by stevevanhooser** [SciCrunch/NIF-Ontology#210]
Hi - 

I am looking for help with 3 queries.

1) Suppose I wanted to verify (in a program that can access the web) that a given string S was the name of a subclass of "nervous system" (UBERON:0001016). Is there a query I can write for that?

2) I thought `http://ontology.neuinfo.org/trees/query/rdfs:subClassOf/UBERON:0001016` might do this, but it only gives a tiny subset: 

```
nervous system
├──adult nervous system
└──insect embryonic/larval nervous system
```

If I inspect UBERON:0001016 here, I get a huge set of children:

`https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001016
`

3) What if I wanted to check that my string S was the name of a subclass of "nervous system" that was at least 2 entries deep? Is there a simple query for that?

Thanks
Steve

**Comment by tgbugs** [comment]
1. One potential solution. The query 
https://scicrunch.org/api/1/sparc-scigraph/vocabulary/term/adult%20nervous%20system?prefix=UBERON
returns json that looks like 
```
[{"iri":"http://purl.obolibrary.org/obo/UBERON_6003559",
  "labels":["adult nervous system"],
  "curie":"UBERON:6003559",
  "categories":["anatomical entity"],
  "synonyms":[],
  "acronyms":[],
  "abbreviations":[],
  "deprecated":false,
  "definitions":["."]}]
```
accessing `blob[0]['curie']` will give you the uberon id `UBERON:6003559` which you can then pass to the graph endpoint using the following query.
https://scicrunch.org/api/1/sparc-scigraph/graph/neighbors/UBERON:6003559?relationshipType=subClassOf&direction=OUTGOING&depth=20
You can then check to see if `UBERON:0001016` is in the nodes of the result. e.g. in python `[n for n in blob['nodes'] if n['id'] == 'UBERON:0001016']`
There is probably a more efficient version of that query using cypher that doesn't make two network requests, but this will work.
For certain high level categories you can also directly check the category field. The list of currently supported categories is
[here](https://github.com/tgbugs/pyontutils/blob/4ce6dc0afdbb12afdc94a00c194be23e98f324be/nifstd/scigraph/graphload-base-template.yaml#L21-L36).
Categories are populated over the transitive closure of the subClassOf hierarchy for that class.

2. In this case the ebi query runs over both the subClassOf and the partOf hierarchies.
The partOf is indicated by the P in the blue circle.
You can see the exact relationship in the term relations box.
I have not [implemented](https://github.com/tgbugs/pyontutils/blob/master/nifstd/nifstd_tools/ontree.py) the ability to query/visualize over more than one relationship at a time.
However, SciGraph does support this. For example
https://scicrunch.org/api/1/sparc-scigraph/graph/neighbors/UBERON:0001016?relationshipType=subClassOf&relationshipType=BFO:0000050&direction=INCOMING&depth=10
will return a result that is similar to the one from EBI.
Beware the issue reported in https://github.com/SciGraph/SciGraph/issues/284 since it results in a 10 fold increase in the data returned (e.g. 24k edges). To work around this you can exclude edges where `edge['meta']['owlType'] == 'BFO:0000051'`.

3. Yes, in the example using `direction=OUTGOING` above change `depth=20` to `depth=2`.

**Comment by stevevanhooser** [comment]
Thanks, Tom, this is a big help, but I'm still a little stuck.

I'll use a more specific example. I would like to use NIF-Ontology as the "vocabulary" for some of the fields in a database we are creating to accompany a software interface to neuroscience data (still under construction, NDI, http://github.com/VH-Lab/NDI-matlab). 

We want to have a field "nervous_system_area" to describe, say, where a probe is inserted. We want to verify that the user has input a nervous system area that is in the NIF-Ontology.

Let's say the user inputs 'LGN'. 

**Step 1: verify the node is in the ontology** 

We can verify that is a node in the ontology using
https://scicrunch.org/api/1/sparc-scigraph/vocabulary/term/LGN?prefix=UBERON
and it comes back great, showing the node UBERON:0001926 in JSON. No problem in Step 1.

**Step 2: verify that the node is subClassOf / partOf 'nervous system' (UBERON:0001016).**
(Ideally, we want to make sure it is at least 2 deeper than UBERON:0001016 because everything that is a direct subClassOf UBERON:0001016 is a category rather than a place in the brain. Maybe there's a better criteria?)

Here I am stuck. 



https://scicrunch.org/api/1/sparc-scigraph/graph/neighbors/UBERON: UBERON:0001926?relationshipType=subClassOf&direction=OUTGOING&depth=20

returns a small graph but as you say does not show all of the relationships in the EBI query, and the relationship to nervous system (UBERON:0001016) is not among these (it is not among the nodes returned).

When I look at the EBF query, there are relationships between UBERON:0001926 and UBERON:0001016, such as (if I understand correctly):

"lateral geniculate body"(UBERON:0001926) is a subclass of "nucleus of dorsal thalamus" which is a part of "dorsal thalamus" which is a part of "dorsal plus ventral thalamus" which is a subclass of "thalamic complex" which is a subclass of "gray matter of diencephalon" which is a subclass of "gray matter of forebrain" which is a part of "brain gray matter" which is a part of "brain" which is a part of "central nervous system" which is a part of "nervous system" (UBERON:0001016). 


Here are my attempts to find all the neighbors:

Failed attempt 1)

 UBERON:0001016 is not among the nodes returned in 

https://scicrunch.org/api/1/sparc-scigraph/graph/neighbors/UBERON:0001926?relationshipType=subClassOf&relationshipType=BFO:0000050&direction=OUTGOING&depth=100

or

https://scicrunch.org/api/1/sparc-scigraph/graph/neighbors/UBERON:0001926?relationshipType=subClassOf&relationshipType=BFO:0000050&direction=INCOMING&depth=100

Failed attempt 2)

I thought "reachablefrom" might be the right command but this is an error:

https://scicrunch.org/api/1/scigraph/graph/reachablefrom/UBERON:0001926?relationships=subClassOf,BFO:0000050
as is this
https://scicrunch.org/api/1/scigraph/graph/reachablefrom/UBERON%3A0001926?relationships=subClassOf,BFO%3A0000050



Any ideas?

Thanks again!

Best
Steve

**Comment by tgbugs** [comment]
This was a bug on my end, the version of SciGraph running in production was a bit out of date and didn't support multiple relationshipType queries.

Failed attempt 1 is the right solution. The query https://scicrunch.org/api/1/sparc-scigraph/graph/neighbors/UBERON:0001926?relationshipType=subClassOf&relationshipType=BFO:0000050&direction=OUTGOING&depth=40 should now be working. I see 83 edges and `UBERON:0001016` is in nodes as expected.

The reachablefrom query won't do what you want since it doesn't take a direction and will also give you everything in the graph that is connected to the starting point via that relationship.

**Comment by stevevanhooser** [comment]
Hi Tom - 

Brilliant! Thanks so much. It works in my hands, too. 

Best
Steve
