### ISSUE TITLE
Remove LDCV from Huang NPOKB:40- it is not an expression phenotype

### ISSUE THREAD

**Issue by memartone** [SciCrunch/NIF-Ontology#220]
It stands for large dense-core vesicles and you can see in Table S7 that it is LDCV release

**Comment by tgbugs** [comment]
LDCV has been removed from the current version since it falls under synaptic properties. When we implement a more granular model for Huang we can probably model these kinds of assertions as entailments on neurons bearing the particular molecular phenotypes that are associated with them in the table.
