### ISSUE TITLE
Exclude synonyms problem

### ISSUE THREAD

**Issue by koweilin** [SciCrunch/NIF-Ontology#97]
When I searched neuron-derived orphan receptor 1(using autocomplete) and selected Type as molecule, and chose NURSA: Molecules...
https://dknet.org/data/source/nif-0000-03208-6/search?q=PR%3A000011410&l=%5Bneuron-derived%20orphan%20receptor%201%20%7BPR%3A000011410%7D%5D

If I click Query Expansion, and click exclude synonyms, and there is no results. There should be result since the neuron-derived orphan receptor 1 is the match in the table view.
https://dknet.org/data/source/nif-0000-03208-6/search?q=PR%3A000011410&l=%5Bneuron-derived%20orphan%20receptor%201%20%7BPR%3A000011410%7D%5D&exclude=synonyms

**Comment by tgbugs** [comment]
This is because the label is `nuclear receptor subfamily 4 group A member 3` and `neuron-derived orphan receptor 1` autocompleted as a synonym. I think the solution to this problem is to make it possible to see what the expansion is on the second page or to change the value that appears in the search box because there is currently no way to see that and the value being searched absolutely does not match what is in the search box. Another thing we should try to do would be to make it clear in the query expansion pane which values were synonyms and which were labels so that people know what they are removing. @fivebillionmph is there a way to do one or both of these?

**Comment by tgbugs** [comment]
I am closing this since it is a SciCrunchUI issue.
